trying to get ci pipeline to work

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -25,27 +25,27 @@ jobs:
       # Step 2: Build the repo to make sure it builds
       - name: Build repo
         run: idf.py build
-        continue-on-error: true
+        # continue-on-error: true
 
-      # Step 3: Install the needed packages for formating
-      - name: Set up Clang-format
-        run: apt-get install -y clang-format
+      # # Step 3: Install the needed packages for formating
+      # - name: Set up Clang-format
+      #   run: apt-get install -y clang-format
 
-      # Step 4: Run the formatter
-      - name: Run Clang-Format
-        run: |
-          find . -name "*.cpp" -o -name "*.c" -o -name "*.h" | xargs clang-format -i
+      # # Step 4: Run the formatter
+      # - name: Run Clang-Format
+      #   run: |
+      #     find . -name "*.cpp" -o -name "*.c" -o -name "*.h" | xargs clang-format -i
 
-      # Step 5: Check for changes
-      - name: Check for formatting changes
-        run: |
-          if [[ $(git status --porcelain) ]]; then
-            echo "Code formatting issues found. Please run Clang-Format.";
-            exit 1;
-          else
-            echo "No formatting issues found.";
-          fi
-        continue-on-error: true # keep going if fails
+      # # Step 5: Check for changes
+      # - name: Check for formatting changes
+      #   run: |
+      #     if [[ $(git status --porcelain) ]]; then
+      #       echo "Code formatting issues found. Please run Clang-Format.";
+      #       exit 1;
+      #     else
+      #       echo "No formatting issues found.";
+      #     fi
+      #   continue-on-error: true # keep going if fails
 
       # Step 6: Set up static analysis
       - name: Set up clang-tidy with idf
